// Synthetic demo fixtures only. Do not add real operator, customer or internal project data here.

export const initialMeasures = [];

export const demoMeasures = [
  {
    id: 'demo_grid_automation',
    active: true,
    externalId: 'SAP-PSP-NA-2027-001',
    orgUnit: 'Netze Strom',
    monitoringProfile: 'nap14d',
    monitoringCategory: 'Optimierung/Verstärkung',
    networkLevel: 'Mittelspannung/Niederspannung',
    reportingRegion: 'Demogebiet Alpha',
    reportingStatus: 'geplant',
    capacityImpact: 'Engpass- und Ausfallfolgen reduziert; Anschlussreserve qualitativ erhöht',
    bottleneckRef: 'MS-Ring Alpha / ONS-Cluster Nord',
    permitRequired: 'no',
    permitStatus: 'keine öffentlich-rechtliche Genehmigung erwartet',
    investmentDecisionStatus: 'planned',
    investmentDecisionDate: '',
    alternativesChecked: 'Manuelle Schaltung und reiner Stationsersatz als Alternativen dokumentieren',
    flexibilityNeed: 'Beobachtbarkeit/Fernsteuerung als Vorstufe für Flexibilitätsnutzung',
    name: 'Netzautomatisierung Demogebiet Alpha',
    type: 'wahl',
    cost: 820,
    year: 2027,
    secure: 70,
    uncertain: 30,
    probability: 60,
    opexRecognition: 60,
    life: 15,
    depr: 'normal',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 0,
    portfolioShare: 35,
    objectiveIds: ['obj_supply', 'obj_eff'],
    opexPa: 18,
    opexDeltaPa: 10,
    reinvestCost: 120,
    decommissionCost: 25,
    decommissionYear: 2042,
    impactAssumptions: [
      {'id':'impact_demo_grid_q','area':'qElement','title':'Weniger lange Versorgungsunterbrechungen','amount':15,'confidence':'assumption','governance':'basis','startYear':2027,'endYear':'','attribution':100,'chain':'Automatisierung grenzt Fehler schneller ein und verkürzt Wiederversorgung im synthetischen Demogebiet.','evidence':'Synthetische Betriebserfahrung aus Demo-Störungsanalyse 2024-2026','evidenceType':'operations','note':'Mit Regulierungsmanagement auf Q-Systematik prüfen.'},
      {'id':'impact_demo_grid_e','area':'efficiency','title':'Weniger manuelle Entstörung und Schaltaufwand','amount':8,'confidence':'assumption','governance':'basis','startYear':2027,'endYear':'','attribution':100,'chain':'Fernsteuerung reduziert Anfahrten und manuelle Schalthandlungen.','evidence':'Expertenschätzung Netzbetrieb','evidenceType':'expert','note':''},
      {'id':'impact_demo_grid_risk','area':'risk','title':'Vermiedene Großstörung im Demogebiet','confidence':'review','governance':'sensitivity','startYear':2027,'endYear':'','attribution':100,'chain':'Automatisierung reduziert Eskalationsrisiko bei Folgefehlern.','evidence':'Synthetischer Risikoworkshop offen','evidenceType':'open','riskProbabilityBefore':8,'riskProbabilityAfter':3,'riskImpact':400,'note':'Nur als Sensitivität bis Freigabe.'}
    ],
    note: 'Abstimmen, ob der Qualitätsbeitrag separat messbar ist oder nur als Portfolioeffekt angesetzt wird.'
  },
  {
    id: 'demo_station_replacement',
    active: true,
    externalId: 'SAP-PSP-ONS-2027-014',
    orgUnit: 'Netze Strom',
    monitoringProfile: 'qreg',
    monitoringCategory: 'Erhalt/Erneuerung',
    networkLevel: 'Niederspannung/Mittelspannung',
    reportingRegion: 'Demogebiet Alpha',
    reportingStatus: 'geplant',
    capacityImpact: 'Fernwirkfähigkeit für Wiederversorgung und Netzbeobachtbarkeit',
    bottleneckRef: 'Trafostation Alpha-14',
    permitRequired: 'no',
    permitStatus: 'nicht erforderlich',
    investmentDecisionStatus: 'planned',
    investmentDecisionDate: '',
    alternativesChecked: 'Nur Ersatz ohne Fernwirkung fachlich verworfen; Begründung noch dokumentieren',
    flexibilityNeed: 'keine direkte Flexibilitätsbeschaffung; Datenbasis für Netzführung',
    templateId: 'tpl_fernwirk_trafo',
    templateVersion: '2026-07',
    name: 'Ersatz Trafostation mit Fernwirkfähigkeit',
    type: 'wahl',
    cost: 540,
    year: 2027,
    secure: 75,
    uncertain: 25,
    probability: 55,
    opexRecognition: 50,
    life: 35,
    depr: 'normal',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 0,
    portfolioShare: 25,
    objectiveIds: ['obj_supply'],
    opexPa: 6,
    opexDeltaPa: 4,
    reinvestCost: 0,
    decommissionCost: 15,
    decommissionYear: 2045,
    impactAssumptions: [
      {'id':'impact_demo_station_q','area':'qElement','title':'Fernwirkfähigkeit reduziert Ausfallminuten','amount':10,'confidence':'proven','governance':'basis','startYear':2027,'endYear':'','attribution':100,'chain':'Störung wird schneller erkannt und eingegrenzt; Wiederversorgungszeit sinkt.','evidence':'Historische Störungen vergleichbarer Stationen','evidenceType':'measurement','note':''},
      {'id':'impact_demo_station_risk','area':'risk','title':'Vermiedene Folgekosten bei Stationsausfall','confidence':'assumption','governance':'basis','startYear':2027,'endYear':'','attribution':100,'chain':'Ersatz reduziert Eintrittswahrscheinlichkeit alterungsbedingter Ausfälle.','evidence':'Asset-Zustandsbewertung und Betriebsschätzung','evidenceType':'operations','riskProbabilityBefore':6,'riskProbabilityAfter':1.5,'riskImpact':400,'note':''}
    ],
    note: 'Technische Umsetzbarkeit im geplanten Inbetriebnahmejahr bestätigen.'
  },
  {
    id: 'demo_pressure_station',
    active: false,
    externalId: 'SAP-PSP-GAS-2029-003',
    orgUnit: 'Netze Gas',
    monitoringProfile: 'monitoring',
    monitoringCategory: 'Erhalt/Erneuerung',
    networkLevel: 'Mitteldruck',
    reportingRegion: 'Netzgebiet Gas Süd',
    reportingStatus: 'geplant',
    capacityImpact: 'Versorgungssicherheit im Mitteldrucknetz stabilisiert',
    bottleneckRef: 'GDRA Süd-3',
    permitRequired: 'unknown',
    permitStatus: 'prüfen',
    investmentDecisionStatus: 'unknown',
    investmentDecisionDate: '',
    alternativesChecked: 'Instandsetzung vs. Modernisierung offen',
    flexibilityNeed: 'kein direkter Flexibilitätsbezug',
    name: 'Modernisierung Gasdruckregelanlage',
    type: 'risiko',
    cost: 610,
    year: 2029,
    secure: 72,
    uncertain: 28,
    probability: 50,
    opexRecognition: 70,
    life: 40,
    depr: 'kanuLinear',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 0,
    portfolioShare: 20,
    objectiveIds: ['obj_supply', 'obj_decarb'],
    opexPa: 8,
    opexDeltaPa: 14,
    reinvestCost: 0,
    reinvestMode: 'assetAddition',
    reinvestLife: 30,
    decommissionCost: 80,
    decommissionYear: 2045,
    gasTransformationPath: 'reinvestment',
    gasAssetScope: 'station',
    gasObligationBasis: 'unclear',
    gasEternityAssumption: 'unclear',
    gasProvisionAssessment: 'notConcrete',
    gasRegulatoryTreatment: 'costPathReview',
    gasTransformationEvidence: 'Synthetischer Gas-Transformationsworkshop: Weiterbetrieb und Erneuerung prüfen; Rückstellungsfrage noch nicht hinreichend konkret.',
    impactAssumptions: [
      {'id':'impact_demo_pressure_e','area':'efficiency','title':'Weniger ungeplante Instandsetzung','amount':6,'confidence':'assumption','governance':'basis','startYear':2027,'endYear':'','attribution':100,'chain':'Modernisierung senkt wiederkehrende Störungs- und Instandsetzungsaufwände.','evidence':'Instandhaltungsplanung','evidenceType':'operations','note':''},
      {'id':'impact_demo_pressure_risk','area':'risk','title':'Vermiedene Versorgungsunterbrechung','confidence':'review','governance':'sensitivity','startYear':2027,'endYear':'','attribution':100,'chain':'Zustandsrisiko sinkt, monetäre Höhe ist noch nicht freigegeben.','evidence':'Asset-Risikomatrix offen','evidenceType':'open','riskProbabilityBefore':5,'riskProbabilityAfter':2,'riskImpact':930,'note':'Prüfung durch Betrieb und VNB erforderlich.'}
    ],
    note: ''
  },
  {
    id: 'demo_sensor_rollout',
    active: false,
    name: 'Sensorik zur Zustands- und Qualitätsüberwachung',
    type: 'wahl',
    cost: 360,
    year: 2028,
    secure: 55,
    uncertain: 35,
    probability: 65,
    opexRecognition: 55,
    life: 12,
    depr: 'normal',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 0,
    portfolioShare: 20,
    objectiveIds: ['obj_supply', 'obj_eff'],
    opexPa: 22,
    opexDeltaPa: 16,
    reinvestCost: 180,
    decommissionCost: 10,
    decommissionYear: 2040,
    impactAssumptions: [
      {'id':'impact_demo_sensor_q','area':'qElement','title':'Frühere Fehlererkennung verbessert Qualitätskennzahl','amount':18,'confidence':'review','governance':'sensitivity','startYear':2027,'endYear':'','attribution':100,'chain':'Sensorik liefert Zustandsdaten vor Störungen; konkrete Q-Wirkung muss aus Ereignisdaten abgeleitet werden.','evidence':'Noch keine belastbare Historie','evidenceType':'open','note':'Prüfpflichtig bis Datengrundlage vorliegt.'},
      {'id':'impact_demo_sensor_e','area':'efficiency','title':'Gezieltere Instandhaltung','amount':12,'confidence':'assumption','governance':'basis','startYear':2027,'endYear':'','attribution':100,'chain':'Zustandsdaten reduzieren Blindleistung in Inspektion und Instandhaltung.','evidence':'Betriebsschätzung','evidenceType':'expert','note':''}
    ],
    note: 'Datengrundlage für Q-/E-Wirkung mit Betrieb und Regulierungsmanagement klären.'
  },
  {
    id: 'demo_line_replacement',
    active: false,
    externalId: 'SAP-PSP-GAS-2029-011',
    orgUnit: 'Netze Gas',
    monitoringProfile: 'monitoring',
    monitoringCategory: 'Transformation/Rückbau',
    networkLevel: 'Mitteldruck',
    reportingRegion: 'Netzgebiet Gas Süd',
    reportingStatus: 'prüfpflichtig',
    name: 'Leitungsabschnitt mit erhöhter Ausfallwahrscheinlichkeit',
    type: 'risiko',
    cost: 740,
    year: 2029,
    secure: 80,
    uncertain: 20,
    probability: 50,
    opexRecognition: 70,
    life: 40,
    depr: 'kanuDegressive',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 0,
    portfolioShare: 0,
    objectiveIds: ['obj_supply', 'obj_decarb'],
    opexPa: 4,
    opexDeltaPa: 9,
    reinvestCost: 0,
    reinvestMode: 'oneOff',
    reinvestLife: 40,
    decommissionCost: 95,
    decommissionYear: 2045,
    gasTransformationPath: 'physicalDismantling',
    gasAssetScope: 'distributionLine',
    gasObligationBasis: 'concession',
    gasEternityAssumption: 'removed',
    gasProvisionAssessment: 'checkProvision',
    gasRegulatoryTreatment: 'kaneuIstCostsReview',
    gasTransformationEvidence: 'Synthetisches Beispiel: Wegfall der Ewigkeitsvermutung, Konzessions-/Wegenutzungsbezug und Rückbaukosten als prüfpflichtige Herleitung dokumentieren.',
    impactAssumptions: [
      {'id':'impact_demo_line_risk','area':'risk','title':'Vermiedener Schadensfall kritischer Leitungsabschnitt','confidence':'review','governance':'sensitivity','startYear':2027,'endYear':'','attribution':100,'chain':'Ersatz senkt Ausfallwahrscheinlichkeit und Folgekosten im kritischen Abschnitt.','evidence':'Risikowert aus Asset-Management noch zu validieren','evidenceType':'open','riskProbabilityBefore':7,'riskProbabilityAfter':1,'riskImpact':750,'note':'Nur Sensitivität bis Schadenshöhe und Eintrittswahrscheinlichkeit bestätigt sind.'}
    ],
    note: 'Risikowert validieren: Schadenshöhe, Eintrittswahrscheinlichkeit und mögliche Bauabhängigkeiten.'
  }
];
