// Synthetic demo fixtures only. Do not add real operator, customer or internal project data here.

export const initialMeasures = [];

export const demoMeasures = [
  {
    id: 'demo_grid_automation',
    active: true,
    externalId: 'SAP-PSP-NA-2027-001',
    orgUnit: 'Netze Strom',
    tags: ['Demo', 'Strom', 'Automatisierung'],
    effectType: 'classic',
    sourceSystem: 'Demo-ERP',
    sourceRecordId: 'NA-2027-001',
    scoringRef: 'DEMO-SCORING-001',
    assetSystemRef: 'ASSET-MS-ALPHA',
    erpRef: 'ERP-NA-2027-001',
    riskDbRef: 'RISK-STROM-ALPHA-01',
    sourceStatus: 'source_available',
    returnPathStatus: 'needs_update',
    riskEvidenceStatus: 'source_available',
    riskOwnerRole: 'Asset Management',
    riskAssessmentStatus: 'in_review',
    monitoringProfile: 'nap14d',
    monitoringCategory: 'Optimierung/Verstärkung',
    networkLevel: 'Mittelspannung/Niederspannung',
    reportingRegion: 'Demogebiet Alpha',
    reportingStatus: 'geplant',
    capacityImpact: 'Engpass- und Ausfallfolgen reduziert; Anschlussreserve qualitativ erhöht',
    regulatoryStatus: 'cabinet_draft_2026_07_29',
    regulatoryStatusLabel: 'Kabinettsentwurf EEG 2027 / Netzanschlusspaket',
    regulatoryStatusDate: '2026-07-29',
    assumptionStatus: 'draft',
    capacityLimitedGridArea: true,
    capacityLimitedTechnology: 'all',
    redispatchCompensationWaiverEnabled: true,
    redispatchCompensationWaiverLimitPct: 20,
    windPriorityArea: false,
    redispatchRiskClass: 'medium',
    annualRevenueAtRiskTeur: 14,
    connectionRequestPowerKw: 500,
    voltageLevel: 'medium_voltage',
    connectionRequestStatus: 'capacity_reserved',
    queueRiskClass: 'medium',
    reservationExpiryDate: '2027-11-30',
    nextRequiredEvidence: '',
    generationConnectionCostContributionEnabled: true,
    connectionCostContributionTeur: 65,
    connectionCostContributionMode: 'user_defined',
    bottleneckRef: 'MS-Ring Alpha / ONS-Cluster Nord',
    permitRequired: 'no',
    permitStatus: 'keine öffentlich-rechtliche Genehmigung erwartet',
    investmentDecisionStatus: 'planned',
    investmentDecisionDate: '',
    alternativesChecked: 'Manuelle Schaltung und reiner Stationsersatz als Alternativen dokumentiert; wirtschaftliche Überleitung bleibt in Befassung.',
    flexibilityNeed: 'Beobachtbarkeit/Fernsteuerung als Vorstufe für Flexibilitätsnutzung',
    name: 'Netzautomatisierung Demogebiet Alpha',
    type: 'wahl',
    cost: 820,
    year: 2027,
    secure: 70,
    uncertain: 30,
    probability: 60,
    opexRecognition: 60,
    life: 15,
    depr: 'normal',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 32,
    portfolioShare: 35,
    objectiveIds: ['obj_supply', 'obj_eff'],
    opexPa: 18,
    opexDeltaPa: 10,
    reinvestCost: 120,
    decommissionCost: 25,
    decommissionYear: 2042,
    impactAssumptions: [
      { id: 'impact_demo_grid_q', area: 'qElement', title: 'Weniger lange Versorgungsunterbrechungen', amount: 15, confidence: 'assumption', governance: 'basis', startYear: 2027, endYear: '', attribution: 100, chain: 'Automatisierung grenzt Fehler schneller ein und verkürzt Wiederversorgung im synthetischen Demogebiet.', evidence: 'Synthetische Betriebserfahrung aus Demo-Störungsanalyse 2024-2026', evidenceType: 'operations', note: 'Mit Regulierungsmanagement auf Q-Systematik prüfen.' },
      { id: 'impact_demo_grid_e', area: 'efficiency', title: 'Weniger manuelle Entstörung und Schaltaufwand', amount: 8, confidence: 'assumption', governance: 'basis', startYear: 2027, endYear: '', attribution: 100, chain: 'Fernsteuerung reduziert Anfahrten und manuelle Schalthandlungen.', evidence: 'Expertenschätzung Netzbetrieb', evidenceType: 'expert', note: '' },
      { id: 'impact_demo_grid_risk', area: 'risk', title: 'Vermiedene Großstörung im Demogebiet', confidence: 'review', governance: 'sensitivity', startYear: 2027, endYear: '', attribution: 100, chain: 'Automatisierung reduziert Eskalationsrisiko bei Folgefehlern.', evidence: 'Synthetischer Risikoworkshop offen', evidenceType: 'open', riskProbabilityBefore: 8, riskProbabilityAfter: 3, riskImpact: 400, note: 'Nur als Sensitivität bis zur nächsten Befassung.' }
    ],
    note: 'Demo-Befassung: Qualitätsbeitrag, Effizienzannahme und Risiko-/Störungswirkung sind getrennt dokumentiert; Rückspielweg in Demo-ERP ist noch nachzuführen.'
  },
  {
    id: 'demo_station_replacement',
    active: true,
    externalId: 'SAP-PSP-ONS-2027-014',
    orgUnit: 'Netze Strom',
    tags: ['Demo', 'Strom', 'Station'],
    effectType: 'classic',
    sourceSystem: 'Demo-ERP',
    sourceRecordId: 'ONS-2027-014',
    assetSystemRef: 'ASSET-ONS-ALPHA-14',
    erpRef: 'ERP-ONS-2027-014',
    sourceStatus: 'validated',
    returnPathStatus: 'documented',
    riskDbRef: 'RISK-STROM-ALPHA-14',
    riskEvidenceStatus: 'validated',
    riskOwnerRole: 'Netzbetrieb',
    riskAssessmentStatus: 'reviewed',
    monitoringProfile: 'qreg',
    monitoringCategory: 'Erhalt/Erneuerung',
    networkLevel: 'Niederspannung/Mittelspannung',
    reportingRegion: 'Demogebiet Alpha',
    reportingStatus: 'geplant',
    capacityImpact: 'Fernwirkfähigkeit für Wiederversorgung und Netzbeobachtbarkeit',
    bottleneckRef: 'Trafostation Alpha-14',
    permitRequired: 'no',
    permitStatus: 'nicht erforderlich',
    investmentDecisionStatus: 'planned',
    investmentDecisionDate: '',
    alternativesChecked: 'Nur Ersatz ohne Fernwirkung fachlich verworfen; Kurzbegründung liegt als Demoannahme vor.',
    flexibilityNeed: 'keine direkte Flexibilitätsbeschaffung; Datenbasis für Netzführung',
    templateId: 'tpl_fernwirk_trafo',
    templateVersion: '2026-07',
    name: 'Ersatz Trafostation mit Fernwirkfähigkeit',
    type: 'wahl',
    cost: 540,
    year: 2027,
    secure: 75,
    uncertain: 25,
    probability: 55,
    opexRecognition: 50,
    life: 35,
    depr: 'normal',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 18,
    portfolioShare: 25,
    objectiveIds: ['obj_supply'],
    opexPa: 6,
    opexDeltaPa: 4,
    reinvestCost: 0,
    decommissionCost: 15,
    decommissionYear: 2045,
    impactAssumptions: [
      { id: 'impact_demo_station_q', area: 'qElement', title: 'Fernwirkfähigkeit reduziert Ausfallminuten', amount: 10, confidence: 'proven', governance: 'basis', startYear: 2027, endYear: '', attribution: 100, chain: 'Störung wird schneller erkannt und eingegrenzt; Wiederversorgungszeit sinkt.', evidence: 'Historische Störungen vergleichbarer synthetischer Stationen', evidenceType: 'measurement', note: '' },
      { id: 'impact_demo_station_risk', area: 'risk', title: 'Vermiedene Folgekosten bei Stationsausfall', confidence: 'assumption', governance: 'basis', startYear: 2027, endYear: '', attribution: 100, chain: 'Ersatz reduziert Eintrittswahrscheinlichkeit alterungsbedingter Ausfälle.', evidence: 'Asset-Zustandsbewertung und Betriebsschätzung', evidenceType: 'operations', riskProbabilityBefore: 6, riskProbabilityAfter: 1.5, riskImpact: 400, note: '' }
    ],
    note: 'Demofall mit weitgehend dokumentierter Systemreferenz und Risiko-Evidenz; geeignet als Vergleich zu offenen Klärfällen.'
  },
  {
    id: 'demo_fault_response_budget',
    active: true,
    externalId: 'SAP-PSP-STOER-2028-002',
    orgUnit: 'Netze Strom',
    tags: ['Demo', 'Störung', 'Evidenz offen'],
    effectType: 'classic',
    sourceSystem: '',
    sourceRecordId: '',
    riskEvidenceStatus: 'stated',
    riskOwnerRole: '',
    riskAssessmentStatus: 'open',
    monitoringProfile: 'qreg',
    monitoringCategory: 'Erhalt/Erneuerung',
    networkLevel: 'Niederspannung',
    reportingRegion: 'Demogebiet Beta',
    reportingStatus: 'prüfpflichtig',
    capacityImpact: 'Störungsfolgen sollen reduziert werden; konkrete Wirkungskette noch offen',
    bottleneckRef: 'NS-Abgang Beta-7',
    permitRequired: 'unknown',
    permitStatus: 'prüfen',
    investmentDecisionStatus: 'candidate',
    investmentDecisionDate: '',
    alternativesChecked: '',
    flexibilityNeed: 'nicht bewertet',
    name: 'Störungsbudget Demogebiet Beta',
    type: 'risiko',
    cost: 180,
    year: 2028,
    secure: 55,
    uncertain: 45,
    probability: 50,
    opexRecognition: 50,
    life: 20,
    depr: 'normal',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 22,
    portfolioShare: 0,
    objectiveIds: [],
    opexPa: 4,
    opexDeltaPa: 3,
    reinvestCost: 0,
    decommissionCost: 0,
    decommissionYear: 0,
    impactAssumptions: [
      { id: 'impact_demo_fault_risk', area: 'risk', title: 'Störungs-/Risikowirkung noch zu belegen', confidence: 'review', governance: 'sensitivity', startYear: 2028, endYear: '', attribution: 100, chain: '', evidence: '', evidenceType: 'open', riskProbabilityBefore: 4, riskProbabilityAfter: 2, riskImpact: 1100, note: 'Demo zeigt bewusst, dass RiskAvoided ohne Wirkungskette/Evidenz einen Kanban-Klärfall erzeugt.' }
    ],
    note: ''
  },
  {
    id: 'demo_flexibility_context',
    active: false,
    externalId: 'FLEX-DEMO-2028-001',
    orgUnit: 'Netze Strom',
    tags: ['Demo', 'Flexibilität', 'AGNeS'],
    effectType: 'flexibility',
    flexibilityUseCase: 'Netzfahrplan / Engpassvermeidung',
    flexibilityStatus: 'pruefpflichtig',
    regulatoryTreatment: 'context_only',
    networkScheduleRequired: true,
    networkScheduleStatus: 'missing',
    networkConstraintRef: 'Engpasskorridor Gamma offen',
    affectedNetworkLevel: 'Mittelspannung',
    activationWindow: '2028-2030',
    dispatchLogic: 'noch nicht definiert',
    avoidedCapexTeur: 320,
    avoidedCapexConfidence: 'working_value',
    deferredCapexTeur: 140,
    deferredCapexFromYear: 2028,
    deferredCapexToYear: 2031,
    capexAvoidanceEvidenceRef: 'Sidecar ctx_demo_strom_flex_open',
    flexOpexPaTeur: 24,
    flexOpexStartYear: 2028,
    flexOpexDurationYears: 3,
    opexRecognitionStatus: 'open',
    opexEvidenceRef: '',
    agnesRelevant: true,
    agnesRole: 'Netzfahrplan',
    agnesIntegrationStatus: 'not_assessed',
    agnesDataNeeded: 'Netzfahrplan, vermiedene/verschobene CAPEX und jährliche Flex-OPEX validieren.',
    name: 'Flexibilitätsprüfung Netzfahrplan Demogebiet Gamma',
    type: 'wahl',
    cost: 0,
    year: 2028,
    secure: 0,
    uncertain: 0,
    probability: 0,
    opexRecognition: 0,
    life: 1,
    depr: 'normal',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 0,
    portfolioShare: 0,
    objectiveIds: ['obj_eff'],
    impactAssumptions: [],
    note: 'Kontextobjekt für die Strom-Flexibilitätslogik: ohne validierten Netzfahrplan nicht als klassische CAPEX-Maßnahme rechnen.'
  },
  {
    id: 'demo_pressure_station',
    active: false,
    externalId: 'SAP-PSP-GAS-2029-003',
    orgUnit: 'Netze Gas',
    tags: ['Demo', 'Gas', 'Transformation'],
    effectType: 'classic',
    sourceSystem: 'Demo-Asset-System',
    sourceRecordId: 'GDRA-SUED-3',
    assetSystemRef: 'ASSET-GAS-GDRA-SUED-3',
    sourceStatus: 'source_available',
    riskEvidenceStatus: 'stated',
    riskOwnerRole: 'Netzbetrieb Gas',
    riskAssessmentStatus: 'in_review',
    monitoringProfile: 'monitoring',
    monitoringCategory: 'Erhalt/Erneuerung',
    networkLevel: 'Mitteldruck',
    reportingRegion: 'Netzgebiet Gas Süd',
    reportingStatus: 'geplant',
    capacityImpact: 'Versorgungssicherheit im Mitteldrucknetz stabilisiert',
    bottleneckRef: 'GDRA Süd-3',
    permitRequired: 'unknown',
    permitStatus: 'prüfen',
    investmentDecisionStatus: 'unknown',
    investmentDecisionDate: '',
    alternativesChecked: 'Instandsetzung vs. Modernisierung offen',
    flexibilityNeed: 'kein direkter Flexibilitätsbezug',
    name: 'Modernisierung Gasdruckregelanlage',
    type: 'risiko',
    cost: 610,
    year: 2029,
    secure: 72,
    uncertain: 28,
    probability: 50,
    opexRecognition: 70,
    life: 40,
    depr: 'kanuLinear',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 0,
    portfolioShare: 20,
    objectiveIds: ['obj_supply', 'obj_decarb'],
    opexPa: 8,
    opexDeltaPa: 14,
    reinvestCost: 0,
    reinvestMode: 'assetAddition',
    reinvestLife: 30,
    decommissionCost: 80,
    decommissionYear: 2045,
    gasTransformationPath: 'reinvestment',
    gasAssetScope: 'station',
    gasObligationBasis: 'unclear',
    gasEternityAssumption: 'unclear',
    gasProvisionAssessment: 'notConcrete',
    gasRegulatoryTreatment: 'costPathReview',
    gasTransformationEvidence: 'Synthetisches Beispiel: Weiterbetrieb, Erneuerung und Rückstellungsfrage als prüfpflichtiger Gas-Transformationspfad.',
    impactAssumptions: [
      { id: 'impact_demo_pressure_e', area: 'efficiency', title: 'Weniger ungeplante Instandsetzung', amount: 6, confidence: 'assumption', governance: 'basis', startYear: 2029, endYear: '', attribution: 100, chain: 'Modernisierung senkt wiederkehrende Störungs- und Instandsetzungsaufwände.', evidence: 'Synthetische Instandhaltungsplanung', evidenceType: 'operations', note: '' },
      { id: 'impact_demo_pressure_risk', area: 'risk', title: 'Vermiedene Versorgungsunterbrechung', confidence: 'review', governance: 'sensitivity', startYear: 2029, endYear: '', attribution: 100, chain: 'Zustandsrisiko sinkt, monetäre Höhe ist noch nicht freigegeben.', evidence: 'Synthetische Asset-Risikomatrix offen', evidenceType: 'open', riskProbabilityBefore: 5, riskProbabilityAfter: 2, riskImpact: 930, note: 'Prüfung durch Betrieb und Regulierungsmanagement erforderlich.' }
    ],
    note: ''
  },
  {
    id: 'demo_line_replacement',
    active: false,
    externalId: 'SAP-PSP-GAS-2029-011',
    orgUnit: 'Netze Gas',
    tags: ['Demo', 'Gas', 'Rückbau'],
    effectType: 'classic',
    sourceSystem: 'Demo-Asset-System',
    sourceRecordId: 'GAS-LINE-SUED-11',
    assetSystemRef: 'ASSET-GAS-LINE-SUED-11',
    sourceStatus: 'source_available',
    monitoringProfile: 'monitoring',
    monitoringCategory: 'Transformation/Rückbau',
    networkLevel: 'Mitteldruck',
    reportingRegion: 'Netzgebiet Gas Süd',
    reportingStatus: 'prüfpflichtig',
    capacityImpact: 'Transformationspfad und mögliche Rückbaupflicht prüfen',
    bottleneckRef: 'Leitungsabschnitt Süd-11',
    permitRequired: 'unknown',
    permitStatus: 'prüfen',
    investmentDecisionStatus: 'candidate',
    name: 'Leitungsabschnitt mit Rückbau-/Stilllegungsprüfung',
    type: 'risiko',
    cost: 740,
    year: 2029,
    secure: 80,
    uncertain: 20,
    probability: 50,
    opexRecognition: 70,
    life: 40,
    depr: 'kanuDegressive',
    qDirect: 0,
    eDirect: 0,
    riskAvoided: 0,
    portfolioShare: 0,
    objectiveIds: ['obj_supply', 'obj_decarb'],
    opexPa: 4,
    opexDeltaPa: 9,
    reinvestCost: 0,
    reinvestMode: 'oneOff',
    reinvestLife: 40,
    decommissionCost: 95,
    decommissionYear: 2045,
    gasTransformationPath: 'physicalDismantling',
    gasAssetScope: 'distributionLine',
    gasObligationBasis: 'concession',
    gasEternityAssumption: 'removed',
    gasProvisionAssessment: 'checkProvision',
    gasRegulatoryTreatment: 'kaneuIstCostsReview',
    gasTransformationEvidence: 'Synthetisches Beispiel: Wegfall der Ewigkeitsvermutung, Konzessions-/Wegenutzungsbezug und Rückbaukosten als prüfpflichtige Herleitung dokumentieren.',
    impactAssumptions: [
      { id: 'impact_demo_line_risk', area: 'risk', title: 'Vermiedener Schadensfall kritischer Leitungsabschnitt', confidence: 'review', governance: 'sensitivity', startYear: 2029, endYear: '', attribution: 100, chain: 'Ersatz oder Rückbau senkt Ausfallwahrscheinlichkeit und Folgekosten im kritischen Abschnitt.', evidence: 'Synthetischer Risikowert aus Asset-Management noch zu validieren', evidenceType: 'open', riskProbabilityBefore: 7, riskProbabilityAfter: 1, riskImpact: 750, note: 'Nur Sensitivität bis Schadenshöhe und Eintrittswahrscheinlichkeit bestätigt sind.' }
    ],
    note: 'Risikowert validieren: Schadenshöhe, Eintrittswahrscheinlichkeit und mögliche Bauabhängigkeiten.'
  }
];

export const demoSidecar = {
  version: '1.0',
  sources: [
    {
      id: 'src_demo_asset_register',
      type: 'system_export',
      title: 'Synthetischer Asset-/ERP-Auszug',
      contains: ['Systemreferenzen', 'PSP-/Objektbezug', 'Rückspielweg'],
      usableFor: ['system_reference', 'asset_mapping'],
      sensitivity: 'public',
      exportStatus: 'allowed'
    },
    {
      id: 'src_demo_risk_workshop',
      type: 'workshop_note',
      title: 'Synthetische Risiko- und Befassungsnotiz',
      contains: ['RiskAvoided-Arbeitswerte', 'offene Wirkungsketten'],
      usableFor: ['risk_effect', 'clarification'],
      sensitivity: 'public',
      exportStatus: 'allowed'
    }
  ],
  objects: [
    {
      id: 'ctx_demo_strom_flex_open',
      type: 'flexibility',
      sidecarType: 'effect_assumption',
      division: 'strom',
      title: 'Netzfahrplan und Flexibilitätsoption Demogebiet Gamma',
      summary: 'Synthetisches Sidecar: Flexibilität ist als Kontext und mögliche wirtschaftliche Überleitung sichtbar, aber ohne validierten Netzfahrplan nicht KPI-wirksam.',
      status: 'pruefpflichtig',
      activationStatus: 'candidate',
      evidenceStatus: 'stated',
      calculationImpact: 'scenario_only',
      linkedMeasures: ['demo_flexibility_context'],
      sourceRefs: ['src_demo_asset_register'],
      openQuestions: [
        'Netzfahrplan fachlich validieren.',
        'Vermiedene oder verschobene CAPEX gegen klassische Ausbaualternative belegen.',
        'Jährliche Flex-OPEX und Laufzeit dokumentieren.'
      ],
      bridgeLogic: {
        description: 'Mögliche OPEX-gegen-CAPEX-Substitution nur als Stresstest-/Szenariotreiber prüfen.',
        economicRelation: 'capex_dependency',
        direction: 'mixed',
        quantificationStatus: 'open',
        quantificationMethod: 'Noch nicht validierter Arbeitswert aus Demo-Netzfahrplan.',
        amount: 320,
        amountUnit: 'TEUR vermiedene CAPEX',
        timeHorizon: '2028-2031',
        sourceRefs: ['src_demo_asset_register'],
        assumptions: ['AGNeS-Relevanz offen', 'Netzfahrplan fehlt'],
        openQuestions: ['Welche klassische Ausbaualternative wird verdrängt?']
      },
      sensitivity: 'public',
      exportStatus: 'allowed',
      ownerRole: 'Netzbetrieb / Regulierung',
      reviewStatus: 'open'
    },
    {
      id: 'ctx_demo_system_return_path',
      type: 'asset_mapping',
      sidecarType: 'system_reference',
      division: 'strom',
      title: 'Rückspielweg ERP / Asset-System / Risikoakte',
      summary: 'Synthetisches Sidecar: zeigt, welche Maßnahmen vollständige Systemreferenzen haben und wo Rückspielwege fehlen.',
      status: 'pruefpflichtig',
      activationStatus: 'not_activated',
      evidenceStatus: 'source_available',
      calculationImpact: 'indirect',
      linkedMeasures: ['demo_grid_automation', 'demo_fault_response_budget'],
      sourceRefs: ['src_demo_asset_register'],
      openQuestions: ['Störungsbudget Demogebiet Beta braucht Quellsystem und Datensatzreferenz.'],
      bridgeLogic: {
        description: '',
        economicRelation: 'none',
        direction: 'none',
        quantificationStatus: 'not_applicable',
        sourceRefs: [],
        assumptions: [],
        openQuestions: []
      },
      sensitivity: 'public',
      exportStatus: 'allowed',
      ownerRole: 'Controlling / Asset Management',
      reviewStatus: 'needs_update'
    },
    {
      id: 'ctx_demo_gas_transformation_path',
      type: 'decommissioning_context',
      sidecarType: 'context',
      division: 'gas',
      title: 'Gas-Pfad: Stilllegung, Rückbau, Rückstellungen',
      summary: 'Synthetischer Gas-Kontext für KANU-/AfA-/Restwert- und Rückstellungsprüfung; keine automatische KPI-Wirkung.',
      status: 'pruefpflichtig',
      activationStatus: 'not_activated',
      evidenceStatus: 'source_available',
      calculationImpact: 'scenario_only',
      linkedMeasures: ['demo_pressure_station', 'demo_line_replacement'],
      sourceRefs: ['src_demo_risk_workshop'],
      openQuestions: [
        'Gebietspfad klassifizieren: Weiterbetrieb, Rückbau, Umwidmung oder H2-Option.',
        'Nutzungsdauer gegen Transformationshorizont und Ewigkeitsvermutung prüfen.',
        'Rückstellungsbedarf und KAnEu-/Ist-Kosten-Behandlung als Befassung dokumentieren.'
      ],
      bridgeLogic: {
        description: 'Gas-Transformationsannahmen sind Szenariotreiber, aber nicht automatisch rechenwirksam.',
        economicRelation: 'timing_effect',
        direction: 'unclear',
        quantificationStatus: 'described',
        quantificationMethod: 'Qualitative Prüfspur; quantitative Überleitung offen.',
        amount: 0,
        amountUnit: '',
        timeHorizon: 'bis 2045',
        sourceRefs: ['src_demo_risk_workshop'],
        assumptions: ['Wegfall Ewigkeitsvermutung prüfen', 'Rückbaupflicht nicht automatisch unterstellen'],
        openQuestions: ['Welche Aktivierungs-/Kostenpfade sind regulatorisch vertretbar?']
      },
      sensitivity: 'public',
      exportStatus: 'allowed',
      ownerRole: 'Regulierungsmanagement / Rechnungswesen',
      reviewStatus: 'open'
    },
    {
      id: 'ctx_demo_data_quality_notes',
      type: 'data_quality',
      sidecarType: 'context',
      division: 'cross_division',
      title: 'Datenqualität Maßnahmennotizen und Ziel-Zuordnung',
      summary: 'Synthetisches Datenqualitätsobjekt für Kanban-Spalte Dokumentation: fehlende Maßnahmennotizen und Aktenziele bleiben sichtbare Arbeit.',
      status: 'pruefpflichtig',
      activationStatus: 'not_activated',
      evidenceStatus: 'missing',
      calculationImpact: 'none',
      linkedMeasures: ['demo_fault_response_budget'],
      sourceRefs: [],
      openQuestions: ['Anlass, Quelle und fachliche Begründung für offene Maßnahme ergänzen.'],
      bridgeLogic: {
        description: '',
        economicRelation: 'none',
        direction: 'none',
        quantificationStatus: 'not_applicable',
        sourceRefs: [],
        assumptions: [],
        openQuestions: []
      },
      sensitivity: 'public',
      exportStatus: 'allowed',
      ownerRole: 'Modellverantwortung',
      reviewStatus: 'open'
    }
  ],
  links: [
    { sourceId: 'ctx_demo_strom_flex_open', targetId: 'demo_flexibility_context', relation: 'explains' },
    { sourceId: 'ctx_demo_gas_transformation_path', targetId: 'demo_line_replacement', relation: 'context_for' }
  ]
};

export const demoClarificationStatus = {
  'risk-evidence:demo_fault_response_budget': {
    status: 'in_review',
    note: 'Wirkungskette und Evidenz für Störungs-/Risikowert noch nicht hinreichend belegt.',
    notes: [
      {
        note: 'Erste Befassung: Maßnahme als bewusst offener Evidenzfall angelegt; Risikoquelle und Wirkungskette sind nachzutragen.',
        author: 'Demo',
        timestamp: '2027-01-12T09:30:00.000Z',
        status: 'in_review'
      }
    ]
  },
  'system-reference:demo_fault_response_budget': {
    status: 'open',
    note: 'Quellsystem und Datensatzreferenz fehlen im Demodatensatz.',
    notes: []
  },
  'target-mapping:demo_fault_response_budget': {
    status: 'open',
    note: 'Ziel-Zuordnung soll in der Befassungs-Workbench nachgetragen werden.',
    notes: []
  },
  'sidecar:ctx_demo_gas_transformation_path': {
    status: 'open',
    note: 'Gas-Transformationspfad ist bewusst als prüfpflichtiger Kontext im Demo-Sidecar angelegt.',
    notes: []
  }
};
